"""Add new tables

Revision ID: b1a4584cb6b7
Revises: fb1378017e9a
Create Date: 2024-09-24 14:58:11.282144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1a4584cb6b7'
down_revision: Union[str, None] = 'fb1378017e9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('profile_pic', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_username'), 'user_profiles', ['username'], unique=True)
    op.add_column('videos', sa.Column('description', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.add_column('videos', sa.Column('upload_time', sa.DateTime(), nullable=True))
    op.add_column('videos', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.add_column('videos', sa.Column('views_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_videos_id'), 'videos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_id'), table_name='videos')
    op.drop_column('videos', 'views_count')
    op.drop_column('videos', 'is_processed')
    op.drop_column('videos', 'upload_time')
    op.drop_column('videos', 'thumbnail_url')
    op.drop_column('videos', 'description')
    op.drop_index(op.f('ix_user_profiles_username'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
